services:
  ros-as5048b:
    image: ghcr.io/rosblox/ros-as5048b:humble
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: "host"
    ipc: host
    pid: host
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    volumes:
      - ~/.ros/turn_count.yaml:/tmp/turn_count.yaml
    environment:
      - UID=${HOST_UID}
      - ROS_DOMAIN_ID
      - I2C_DEVICE=1
      - I2C_ADDRESS=0x40
    command: su - ros --whitelist-environment=ROS_DOMAIN_ID,I2C_DEVICE,I2C_ADDRESS /run.sh
